app:
  name: "gRPCCalculator"
  version: "1.0.0"

server:
  host: "0.0.0.0"
  port: "8080"
  
  # Можно менять
  comptuing_power: 13
  TIME_ADDITION_MS: 100
  TIME_SUBTRACTION_MS: 100
  TIME_MULTIPLICATIONS_MS: 300
  TIME_DIVISIONS_MS: 400

database:
  dbPath: "./storage/calculator.db"
  migrationsPath: "./migrations"

auth:
  jwt_secret: "yandex-go"
  token_expires: "24h"
