FROM golang:1.24-alpine AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN apk update && apk add --no-cache gcc musl-dev
ENV CGO_ENABLED=1 \
    GOOS=linux \
    GOARCH=amd64

RUN go mod download
COPY . .
RUN go build -o main ./cmd/orchestrator/main.go

FROM alpine:latest
WORKDIR /app/cmd/orchestrator
COPY --from=builder ./app .
ENTRYPOINT ["./main"]
