FROM golang:1.24-alpine AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o main ./web/main.go

FROM alpine:latest
WORKDIR /app/web
COPY --from=builder /app .
EXPOSE 8081
ENTRYPOINT ["./main"]
